

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[](bold green)' # [󰘧, 󰏰, , 󱉸, ➜, $, , 󰘧 ] The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol   = '[󰯆](bold red)'   # [✖, 󰯇, 󰯆]
vimcmd_symbol   = '[](bold cyan)'   # [✖, 󰯇, 󰯆, , ]

[directory]
truncation_length = 4
disabled = false
#format = "[$path]($style)[$lock_symbol]($lock_style) "

#[username]
#format = '\[[$user]($style)\]'

[username]
style_user = 'fg:220 bold'
style_root = 'red bold'
format = '[\[](bold fg:red)[$user]($style)[@](bold fg:148)'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$hostname](bold fg:111)[\]](bold red)[:](bold blue)'
#trim_at = "-"
style = "bold dimmed white"
disabled = false




#[battery]
#full_symbol = "🔋"
#charging_symbol = "🔌"
#discharging_symbol = "⚡"

#[[battery.display]]
#threshold = 30
#style = "bold red"

#[character]
#error_symbol = "[✖  ](bold red) "

#[cmd_duration]
#min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
#format = " took [$duration]($style)"

#[directory]
#truncation_length = 5
#format = "[$path]($style)[$lock_symbol]($lock_style) "

#[git_branch]
#format = " [$symbol$branch]($style) "
#symbol = "🍣 "
#style = "bold yellow"

#[git_commit]
#commit_hash_length = 8
#style = "bold white"

#[git_state]
#format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
conflicted = "⚔️ "
ahead = "🏎️ 💨 ×${count}"
behind = "🐢 ×${count}"
diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count}"
untracked = "🛤️  ×${count}"
stashed = "📦 "
modified = "📝 ×${count}"
staged = "🗃️  ×${count}"
renamed = "📛 ×${count}"
deleted = "🗑️  ×${count}"
#style = "bright-white"
#format = "$all_status$ahead_behind"

#[hostname]
#ssh_only = true
#format = "<[$hostname]($style)>"
#trim_at = "-"
#style = "bold dimmed white"
#disabled = true

#[julia]
#format = "[$symbol$version]($style) "
#symbol = "ஃ "
#style = "bold green"

#[memory_usage]
#format = "$symbol[${ram}( | ${swap})]($style) "
#threshold = 70
#style = "bold dimmed white"
#disabled = false

#[package]
#disabled = true

#[python]
#format = "[$symbol$version]($style) "
#style = "bold green"

#[rust]
#format = "[$symbol$version]($style) "
#style = "bold green"

#[time]
#time_format = "%T"
#format = "🕙 $time($style) "
#style = "bright-white"
#disabled = false

#[username]
#style_user = "bold dimmed blue"
#show_always = false

#[nodejs]
#format = "via [🤖 $version](bold green) "
[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[bun]
format = '\[[$symbol($version)]($style)\]'

[c]
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[cobol]
format = '\[[$symbol($version)]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'

[crystal]
format = '\[[$symbol($version)]($style)\]'

[daml]
format = '\[[$symbol($version)]($style)\]'

[dart]
format = '\[[$symbol($version)]($style)\]'

[deno]
format = '\[[$symbol($version)]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
format = '\[[$symbol($version)]($style)\]'

[erlang]
format = '\[[$symbol($version)]($style)\]'

[fennel]
format = '\[[$symbol($version)]($style)\]'

[fossil_branch]
format = '\[[$symbol$branch]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

#[golang]
##format = 'via [🏎💨 $version](bold cyan) '
#format = 'via [$symbol](bold cyan)[$version](fg:118) '
#symbol = " "   #   󰟓

[golang]
format = '\[[$symbol]($style)[$version](fg:118)\]'
symbol = " "   #   󰟓

[gradle]
format = '\[[$symbol($version)]($style)\]'

[guix_shell]
format = '\[[$symbol]($style)\]'

[haskell]
format = '\[[$symbol($version)]($style)\]'

[haxe]
format = '\[[$symbol($version)]($style)\]'

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'

[java]
format = '\[[$symbol($version)]($style)\]'

[julia]
format = '\[[$symbol($version)]($style)\]'

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[meson]
format = '\[[$symbol$project]($style)\]'

[nim]
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[opa]
format = '\[[$symbol($version)]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
format = '\[[$symbol]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'

[perl]
format = '\[[$symbol($version)]($style)\]'

[php]
format = '\[[$symbol($version)]($style)\]'

[pijul_channel]
format = '\[[$symbol$channel]($style)\]'

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
format = '\[[$symbol($version)]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'

[scala]
format = '\[[$symbol($version)]($style)\]'

[spack]
format = '\[[$symbol$environment]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'

[swift]
format = '\[[$symbol($version)]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'

[solidity]
format = '\[[$symbol($version)]($style)\]'
